### PR TITLE
fix(core): Fix includeWebFeedback crash by stubbing browser wrapper modules

### LINKED ISSUE #6149: Docs example for includeWebFeedback/includeWebReplay crashes at startup
### What React Native libraries do you use?

React Native without Frameworks, RN New Architecture, Hermes, React Navigation

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### Are you using any other error monitoring solution alongside Sentry?

No

### Other Error Monitoring Solution Name

_No response_

### @sentry/react-native SDK Version

8.10.0

### How does your development environment look like?

````
  react-native:
    installed: 0.81.6
````

### Sentry.init()

````js
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  environment: '...',
  integrations: [sentryNavigationIntegration],
  tracesSampleRate: 0.1,
  profilesSampleRate: 0.1,
  sendDefaultPii: false,
  attachScreenshot: false,
  attachViewHierarchy: false,
  enableAutoPerformanceTracing: true,
  enableNativeFramesTracking: true,
});
````

### Steps to Reproduce

Build and run the app

### Expected Result

Doesn't crash

### Actual Result

Following the official "Reduce Bundle Size" docs for the metro config setup:

https://docs.sentry.io/platforms/react-native/manual-setup/metro/#reduce-bundle-size

```
  module.exports = withSentryConfig(config, {
    includeWebReplay: false,
    includeWebFeedback: false,
  });
```

**Crash**

```
[runtime not ready]: TypeError: ... buildFeedbackIntegration is not a function (it is undefined)
```

Thrown at module evaluation, before any app code runs.

### PR DESCRIPTION
**Pull request by antonis**
## :loudspeaker: Type of change
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

When `includeWebFeedback: false` is set in the Metro config, the app crashes at startup with:

```
TypeError: buildFeedbackIntegration is not a function (it is undefined)
```

**Root cause:** The feedback resolver stubs `@sentry-internal/feedback` to an empty module, but `@sentry/browser`'s barrel file imports `./feedbackSync.js` and `./feedbackAsync.js`, which **call** `buildFeedbackIntegration()` at module evaluation time. Since the feedback package is empty, the function is `undefined` and the call crashes before any app code runs.

This differs from replay (`includeWebReplay: false`), which works because `@sentry/browser` only re-exports symbols from `@sentry-internal/replay` without calling them at evaluation time.

**Fix:** The feedback resolver now also stubs `feedbackSync.js` and `feedbackAsync.js` when imported from `@sentry/browser`, preventing them from evaluating and calling into the empty module. The `buildSentryPackageExcludeResolver` helper is changed from a `RegExp` to a `shouldExcludeModule` function to support this origin-aware matching.

## :bulb: Motivation and Context

Fixes https://github.com/getsentry/sentry-react-native/issues/6149

Introduced in https://github.com/getsentry/sentry-react-native/pull/6025 — the `includeWebFeedback` option was modeled after `includeWebReplay`, but feedback has a different integration pattern in `@sentry/browser` (eager function call vs plain re-export).

## :green_heart: How did you test it?

- Added 16 unit tests for the wrapper module exclusion (`feedbackSync.js`, `feedbackAsync.js`)
- Added an integration-style test that simulates all `@sentry/browser` barrel imports and verifies only feedback-related modules are stubbed
- All 169 tests pass (142 existing + 27 new)
- Build and lint pass

## :pencil: Checklist
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [x] I updated the docs if needed. https://github.com/getsentry/sentry-docs/pull/17775
- [x] I updated the wizard if needed.
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Review by lucas-zimerman — APPROVED** [review]
LGTM!
