### ISSUE TITLE
IOS Build failed in Xcode 16

### ISSUE THREAD

**Issue by Bayramito** [getsentry/sentry-react-native#4095]
### ❗ Update from the maintainers: For building with **Xcode 16** you need to

- Use `@sentry/react-native` version 5.31.0 or newer.
- Set APPLICATION_EXTENSION_API_ONLY=YES for Sentry like so:
```ruby
post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'Sentry'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
      else
        # configuration for other targets
      end
    end
  end
end
```

We're investigating how we can make the second step unnecessary (related: https://github.com/getsentry/sentry-react-native/issues/3908).

---

### Description

I just updated my mac to  MACOS 15. And also updated Sentry version to latest which is 5.32 but i started to get this build error in Xcode.

Previously i was using xcode 15 and macOS Sonoma and 5.19 of Sentry. 

![Image](https://github.com/user-attachments/assets/c719a152-af13-467d-b112-38d951436f4d)

My setup
    "@sentry/react-native": "^5.32.0",
    "react-native": "0.72.14",
    XCode: Version 16.0 (16A242d)

**Comment by LeandroTamola** [comment]
Same here using expo and development client.

**Comment by tommynordli** [comment]
Fixed it by updating react-native to 0.75 ([React Native 0.75 is now available with Expo SDK 51](https://expo.dev/changelog/2024/08-14-react-native-0.75)) and sentry to 5.32

**Comment by Bayramito** [comment]
> Fixed it by updating react-native to 0.75 ([React Native 0.75 is now available with Expo SDK 51](https://expo.dev/changelog/2024/08-14-react-native-0.75)) and sentry to 5.32

Thanks but that's not a solution :) Especially if your project scale is a bit bigger than regular

**Comment by teekirol** [comment]
I was able to resolve this by upgrading to @sentry/react-native 5.32.0. I am still using React Native 0.73 and Expo 50.

**Comment by montasaurus** [comment]
Make sure you explicitly specify the version, npm is currently showing an older version as the latest
```
npm i @sentry/react-native@5.32.0
```
![Image](https://github.com/user-attachments/assets/17124ade-b185-45f8-b942-ff50b1ce10cc)

**Comment by haileyok** [comment]
Upgrading to 5.32.0 does indeed allow us to build the app, however we're seeing a crash in production builds:

`-[__NSArrayM length]: unrecognized selector sent to instance 0x303720720`

This is coming from https://github.com/getsentry/sentry-react-native/blob/main/ios/RNSentry.mm#L455, where sometimes `captureEnvelope` is being called with an array rather than a string. Adding a small hack here (https://github.com/bluesky-social/social-app/pull/5400) prevents the crash, though I haven't been able to spend any time to investigate where it is being called with an array rather than string. (It looks like the old behavior - which changed in https://github.com/getsentry/sentry-react-native/commit/f15994e2193153d47e658beabd73243935d022f4 - did call it with an array).

I'll open a separate issue with this as well once I verify this isn't a bizarre cache issue.

**Comment by darix795** [comment]
I upgrade to versions 5.24.0, 5.24.3 and 5.32 with react native 0.74.5 but the problem wasn't fixed.
Same issue in sentry-cocoa repo https://github.com/getsentry/sentry-cocoa/issues/4339

**Comment by Bayramito** [comment]
> I upgrade to versions 5.24.0, 5.24.3 and 5.32 with react native 0.74.5 but the problem wasn't fixed. Same issue in sentry-cocoa repo [getsentry/sentry-cocoa#4339](https://github.com/getsentry/sentry-cocoa/issues/4339)
> 
> `Use of undeclared identifier 'SentryLog'`

Only upgrading did not fixed on me either, you also need to apply this  in your Podfile.

```
if target.name != "Sentry"              config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end

```

**Comment by darix795** [comment]
> > I upgrade to versions 5.24.0, 5.24.3 and 5.32 with react native 0.74.5 but the problem wasn't fixed. Same issue in sentry-cocoa repo [getsentry/sentry-cocoa#4339](https://github.com/getsentry/sentry-cocoa/issues/4339)
> > `Use of undeclared identifier 'SentryLog'`
> 
> Only upgrading did not fixed on me either, you also need to apply this in your Podfile.
> 
> ```
> if target.name != "Sentry"           
>    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO' 
> end
> ```

Thanks! It seems to work only with version 5.32.0.

Is this a bug or an expected behaviour?
I hope this will integrate in future versions.

**Comment by jrodriguer** [comment]
> > I upgrade to versions 5.24.0, 5.24.3 and 5.32 with react native 0.74.5 but the problem wasn't fixed. Same issue in sentry-cocoa repo [getsentry/sentry-cocoa#4339](https://github.com/getsentry/sentry-cocoa/issues/4339)
> > `Use of undeclared identifier 'SentryLog'`
> 
> Only upgrading did not fixed on me either, you also need to apply this in your Podfile.
> 
> ```
> if target.name != "Sentry"           
>    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO' 
> end
> ```

Same error for 'Sentry' installed package.

![Image](https://github.com/user-attachments/assets/5b861242-0bc3-4338-9731-67b40e6cb161)

I updated with recommended settings (Xcode warnings) and add condition to disable APPLICATION_EXTENSION_API_ONLY for non-Sentry targets.

Any recommendations?

**Comment by jrodriguer** [comment]
> > > I upgrade to versions 5.24.0, 5.24.3 and 5.32 with react native 0.74.5 but the problem wasn't fixed. Same issue in sentry-cocoa repo [getsentry/sentry-cocoa#4339](https://github.com/getsentry/sentry-cocoa/issues/4339)
> > > `Use of undeclared identifier 'SentryLog'`
> > 
> > 
> > Only upgrading did not fixed on me either, you also need to apply this in your Podfile.
> > ```
> > if target.name != "Sentry"           
> >    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO' 
> > end
> > ```
> 
> Same error for 'Sentry' installed package.
> 
> ![Image](https://github.com/user-attachments/assets/5b861242-0bc3-4338-9731-67b40e6cb161)
> 
> I updated with recommended settings (Xcode warnings) and add condition to disable APPLICATION_EXTENSION_API_ONLY for non-Sentry targets.
> 
> ```
> platform :ios, '16'
> 
> target '' do
>   use_frameworks!
> 
>   pod 'Sentry'
> 
> end
> 
> post_install do |installer|
>   installer.aggregate_targets.each do |target|
>       target.xcconfigs.each do |variant, xcconfig|
>         xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
>         IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
>       end
>     end
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
>           xcconfig_path = config.base_configuration_reference.real_path
>           IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
>         end
>         if target.name != "Sentry"
>           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>         end
>       end
>     end
> end
> ```
> 
> Any recommendations?

I think it would be more correct to pass this question to the appropriate repository, [sentry-cocoa](https://github.com/getsentry/sentry-cocoa) 😳

**Comment by kahest** [comment]
@jrodriguer which version of the SDK are you using? For building with Xcode 16 you need to update to `5.31.0` or newer.

**Comment by kahest** [comment]
❗ Please note: For building with **Xcode 16** you need to
- Use `@sentry/react-native` version 5.31.0 or newer.
- Set APPLICATION_EXTENSION_API_ONLY=YES for Sentry like so:
```installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name != "Sentry"
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
```

We're investigating how we can make the second step unnecessary.

**Comment by jrodriguer** [comment]
> [@jrodriguer](https://github.com/jrodriguer) which version of the SDK are you using? For building with Xcode 16 you need to update to `5.31.0` or newer.



> ❗ Please note: For building with **Xcode 16** you need to
> 
> * Use `@sentry/react-native` version 5.31.0 or newer.
> * Set APPLICATION_EXTENSION_API_ONLY=YES for Sentry like so:
> 
> ```
>     target.build_configurations.each do |config|
>       if target.name != "Sentry"
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
> ```
> 
> We're investigating how we can make the second step unnecessary (related: [#3908](https://github.com/getsentry/sentry-react-native/issues/3908)).

I don't have react-native, if not an IOS project with Pod as a dependency manager.
The second step working fine.

I have updated `Sentry` to the latest version, now everything is correct.

**Comment by osbornZ** [comment]
```
No type named 'terminate_handler' in
namespace 'std'
& No member named 'set_terminate' in
namespace 'std'
x No type named'set_terminate' in
namespace 'std'
```
I got error when my xcode update to 16.0，and when  i  use         

"@sentry/react-native": "^5.31.0",
and set 
if target.name != "Sentry"           
   config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO' 
end

rebuild  there toast system crash： 

```
Process:               XCBBuildService [5771]
Path:                  /Applications/Xcode.app/Contents/SharedFrameworks/XCBuild.framework/Versions/A/PlugIns/XCBBuildService.bundle/Contents/MacOS/XCBBuildService

```

**Comment by kailashAppDev** [comment]
I'm getting this error with expo ^51.0.18, react native 0.74.3 and sentry ~5.32.0

> /ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sentry' from project 'Pods')

**Comment by tmcjunkinmarquis** [comment]
I am getting this error with the latest Xcode and 
"expo": "^49.0.0",
"react-native": "0.72.6",
"@sentry/react-native": "5.32.0"
and made the changes recommend by @kahest .
Thank you for working on it.

**Comment by peyman-se** [comment]
This combination for expo worked for us:

Expo: 51.0.31
sentry/react-native:  5.24.3

**Comment by iamthemuhammadirfan** [comment]
Will the upgradation of package corrupt the implementation as well?
Mine react native version is 0.72.4
and my package version is 5.33.0
Even after updating to swift6 from build setting I'm getting this error 

![Image](https://github.com/user-attachments/assets/dc9d4843-7076-488c-94bd-416d3a2bf74b)

**Comment by JoaoPauloCMarra** [comment]
![Image](https://github.com/user-attachments/assets/b319a11a-e3e4-4c71-9527-9c42cb8c4462)
same here preventing EAS builds

**Comment by bytemtek** [comment]
This versions work without problem.

"@sentry/react-native": "5.33.0",
"expo": "^51.0.32",

**Comment by kahest** [comment]
@JoaoPauloCMarra the warning comes from Expo recommending a specific version of `@sentry/react-native` - we have multiple reports that it works fine with `5.24.3` and `5.33.1`, so this should not prevent you building and testing the app

**Comment by tmcjunkinmarquis** [comment]
@kahest , yes, I made the change to the Podfile also.

**Comment by fbeccaceci** [comment]
> [@JoaoPauloCMarra](https://github.com/JoaoPauloCMarra) the warning comes from Expo recommending a specific version of `@sentry/react-native` - we have multiple reports that it works fine with `5.24.3` and `5.33.1`, so this should not prevent you building and testing the app

It builds with 5.33.1 but the sourcemaps are not uploaded automatically so all errors show up unsymolicated

**Comment by kahest** [comment]
@fbeccaceci do you use RN 0.75.x? There is a separate issue tracking a potential problem with that version here: https://github.com/getsentry/sentry-react-native/issues/4120

**Comment by fbeccaceci** [comment]
@kahest no, still on 0.74.3 which is the default with expo sdk 51

**Comment by kahest** [comment]
Quick update - we're working on getting Expo's dependency updated. We're also investigating some reports of source maps not being uploaded correctly with Xcode 16, but weren't able to reproduce this. If you have more info - ideally a repro - please let us know

**Comment by JoaoPauloCMarra** [comment]
> Quick update - we're working on getting Expo's dependency updated. We're also investigating some reports of source maps not being uploaded correctly with Xcode 16, but weren't able to reproduce this. If you have more info - ideally a repro - please let us know

[created this PR related to the version update](https://github.com/expo/expo/pull/31680)

**Comment by shehryar-munir** [comment]
Xcode 16, React Native version `0.64`, `"@sentry/react-native": "^5.31.0",`
Facing this isuse when trying to build IOS app from xcode
Undefined symbols for architecture x86_64:
  "_swift_willThrowTypedImpl", referenced from:
      _swift_willThrowTyped in libSentry.a[272](SentryOnDemandReplay.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by maimai886** [comment]
In my case, I’m using an older version of RN and Sentry, and the following error occurred.
"react-native": "0.61.2"
No type named 'terminate_handler' in namespace 'std'
No member named 'set_terminate' in namespace 'std'
No type named 'set_terminate' in namespace 'std'

After adding this code at the bottom of the Podfile, it can run successfully.

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Sentry'

      file_path = 'Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp'
      contents = File.read(file_path)
      unless contents.include?('#include <exception>')
        FileUtils.chmod('u+w', file_path)
        File.open(file_path, 'w') do |file|
          file.puts('#include <exception>')
          file.puts(contents)
        end
      end
      file_path = 'Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c'
      contents = File.read(file_path)
      unless contents.include?('#include <sys/_types/_ucontext64.h>')
        FileUtils.chmod('u+w', file_path)
        File.open(file_path, 'w') do |file|
          file.puts('#include <sys/_types/_ucontext64.h>')
          file.puts(contents)
        end
      end

    end
  end
end
`

**Comment by carlosriveroib** [comment]
> I'm getting this error with expo ^51.0.18, react native 0.74.3 and sentry ~5.32.0
> 
> > /ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sentry' from project 'Pods')

same here

**Comment by krystofwoldrich** [comment]
@maimai886 Thank you for posting the workaround for RN 0.61.2 and Xcode 16. Is there anything else we can do for you? If so please open a new issue where we can track it.

Currently RN 0.65 and older are unsupported by both the Sentry RN SDK and byt [the React Native team](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#what-versions-are-currently-supported).

**Comment by krystofwoldrich** [comment]
@shehryar-munir Thank you for reporting the issue with RN 0.64, Xcode 16 and `@sentry/react-native@5.31.0`. Sadly RN 0.64 is unsupported by the SDK and also by [the RN team](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#what-versions-are-currently-supported). 

What Sentry RN SDK version were you using before upgrading to Xcode 16?

**Comment by wdifruscio** [comment]
This is so frustrating.. since the new xcode was released i think I am going to have to spend who knows how long figuring out how to rebuild this app to work on the latest RN version

Anyway, I started having this issue on 0.69.6 and 4.2.2

I wasn't having it yesterday but I ran a new prebuild in an attempt to fix some other deps and now this is causing me pain again, hopefully I can upgrade to a minor version bump to resolve

I also noticed on the older version that there was a bitcode error when uploading to app store with xcode16 and 4.2.2 - if relevant for whoever reads this lol

**Comment by luizhfff** [comment]
Hey all, hope everyone is doing good!

We have a React Native project and after Xcode was updated to v16 we started having issues related to Sentry package.

We were using:
```
"@sentry/react-native": "^5.15.1",
"@sentry/cli": "2.21.2",

```
```
"react": "17.0.2",
"react-native": "0.68.6",
```

Issue when building app in xcode:
![Image](https://github.com/user-attachments/assets/5a62432c-c8c1-4bd8-bec1-995f06c9feb8)


Then I saw that this might have been fixed in newer version, but after updating I am not able to distribute app to testflight. I get this error below, even though I have settings set to NOT enable bitcode:
```
 "@sentry/cli": "^2.36.6",
 "@sentry/react-native": "^5.33.1",
```

![Image](https://github.com/user-attachments/assets/148e453e-425b-45a5-b0b7-bee4496e20c4)
![Image](https://github.com/user-attachments/assets/2f7c6c4d-86d6-4c66-b90f-47466c0960f6)


Unfortunately updating React Native and React is not an option at the moment 😢 

Has anyone been able to fix this issue?

**Comment by krystofwoldrich** [comment]
Hi @wdifruscio,
we understand the frustration.

Let us know if https://github.com/getsentry/sentry-react-native/releases/tag/5.31.1 works for you.

This and later v5 version don't have any known issues with the Xcode 16.

**Comment by duynghiale** [comment]
> I'm also getting build errors on the latest Xcode
> 
> ```
> CompileC /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.o /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Sentry' from project 'Pods')
>     cd /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods
>     
>     Using response file: /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp
>     
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /Users/tommy/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.0-22A3362-db63dc9361471f152f572502bdbfe70a.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/tommy/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Index.noindex/DataStore @/Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -include /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Target\ Support\ Files/Sentry/Sentry-prefix.pch -MMD -MT dependencies -MF /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.d --serialize-diagnostics /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.dia -c /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp -o /Users/tommy/Library/Developer/Xcode/DerivedData/MyApp-bswewohvzvjjatfonkbgcibsndjn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/Sentry.build/Objects-normal/arm64/SentryCrashMonitor_CPPException.o
> /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:60:13: error: no type named 'terminate_handler' in namespace 'std'
>    60 | static std::terminate_handler g_originalTerminateHandler;
>       |        ~~~~~^
> /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:206:47: error: no member named 'set_terminate' in namespace 'std'
>   206 |             g_originalTerminateHandler = std::set_terminate(CPPExceptionTerminate);
>       |                                          ~~~~~^
> /Users/tommy/Git/myApp/app.worktrees/fix-bg-location/ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:208:18: error: no type named 'set_terminate' in namespace 'std'
>   208 |             std::set_terminate(g_originalTerminateHandler);
>       |             ~~~~~^
> 3 errors generated.
> ```
> 
> ![Image](https://github.com/user-attachments/assets/27fece78-83ac-4cfc-bbc2-6219ea4e8404)

how do you fix it ?

**Comment by stackchain** [comment]
Hey, I see it was closed, yet when trying to build with new sentry package it throws some weird error (android + iOS)

**Comment by wdifruscio** [comment]
> Hi [@wdifruscio](https://github.com/wdifruscio), we understand the frustration.
> 
> Let us know if https://github.com/getsentry/sentry-react-native/releases/tag/5.31.1 works for you.
> 
> This and later v5 version don't have any known issues with the Xcode 16.

I was luckily, after much pain, able to build on the latest sentry version and 0.69.9 without too many hiccups, I feel like react native developers should have the xcode release dates in their calendar to make sure all major releases are deployed beforehand -_-

**Comment by shtefanilie** [comment]
> I was able to resolve this by upgrading to @sentry/react-native 5.32.0. I am still using React Native 0.73 and Expo 50.

I bumped even to `5.35.0` as this was the latest. Also, currently on 0.73.2, barebones, without expo. 
I did run `pod deintegrate` and `pod repo update`. After that `pod install` and all went well 💯

**Comment by femathic** [comment]
> Xcode 16, React Native version `0.64`, `"@sentry/react-native": "^5.31.0",` Facing this isuse when trying to build IOS app from xcode
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_swift_willThrowTypedImpl", referenced from:
>       _swift_willThrowTyped in libSentry.a[272](SentryOnDemandReplay.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

Please were you able to fix this?

**Comment by krystofwoldrich** [comment]
Hi @femathic,
if you are experiencing a similar error, please open a new issue with the details about your application.

**Comment by Aaron46** [comment]
Came here to add for anyone using expo and has this issue, this is a usable config plugin:
```
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Renamed from withIosCppStandard to withIosConfig to reflect broader purpose
const withIosConfig = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );
      let podfileContent = fs.readFileSync(podfilePath, 'utf8');

      // Snippet to inject - Fix for Sentry with Xcode 16
      const configSnippet = `
    # Fix for Sentry with Xcode 16
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'Sentry'
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
        end
      end
    end
`;

      // Target line pattern (looks for the start of the call)
      const targetLinePattern = /react_native_post_install\(/;
      // Check if snippet already exists
      const snippetExists = podfileContent.includes(
        "config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'"
      );

      if (snippetExists) {
        console.log('iOS configuration already set in Podfile. Skipping.');
      } else {
        const lines = podfileContent.split('\n');
        let targetLineIndex = -1;
        let blockEndLineIndex = -1;

        // Find the line index containing the target pattern
        for (let i = 0; i < lines.length; i++) {
          if (targetLinePattern.test(lines[i])) {
            // Found the start of the call, now find where the call actually ends
            let openParens = 0;
            let foundEnd = false;
            for (let j = i; j < lines.length; j++) {
              openParens += (lines[j].match(/\(/g) || []).length;
              openParens -= (lines[j].match(/\)/g) || []).length;
              // Check if the line contains a closing parenthesis and balance is 0
              if (lines[j].includes(')') && openParens === 0) {
                targetLineIndex = j; // Line where the call ends
                foundEnd = true;
                break;
              }
            }
             if (foundEnd) break;
             else targetLineIndex = -1; // Reset if closing paren wasn't found within reasonable limits
          }
        }

        if (targetLineIndex !== -1) {
          // Insert the snippet after the target line where the call ends
          lines.splice(targetLineIndex + 1, 0, configSnippet);
          podfileContent = lines.join('\n');
          fs.writeFileSync(podfilePath, podfileContent);
          console.log('Updated iOS configuration in Podfile via config plugin (Sentry fix for Xcode 16).');
        } else {
          console.warn(
            'Could not find react_native_post_install hook line in Podfile to set iOS configuration via config plugin.'
          );
        }
      }

      return config;
    },
  ]);
};

module.exports = withIosConfig;
```
Place in plugins directory and use in app.json in plugins key likethis:
```
    "plugins": [
      ...
      "./plugins/withIosConfig.js"
    ],
```

**Comment by 96vini** [comment]
I'm fixed using `"@sentry/react-native": "^6.16.0",`
