### ISSUE TITLE
Build fails on Xcode 16.0 Beta

### ISSUE THREAD

**Issue by Mitch528** [getsentry/sentry-react-native#3883]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 5.23.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

Fails to build on Xcode 16.0 Beta (16A5171c)

```
ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:60:13: error: no type named 'terminate_handler' in namespace 'std'
   60 | static std::terminate_handler g_originalTerminateHandler;
      |        ~~~~~^
ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:207:47: error: no member named 'set_terminate' in namespace 'std'
  207 |             g_originalTerminateHandler = std::set_terminate(CPPExceptionTerminate);
      |                                          ~~~~~^
ios/Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:209:18: error: no type named 'set_terminate' in namespace 'std'
  209 |             std::set_terminate(g_originalTerminateHandler);
      |             ~~~~~^
```

**Steps to reproduce:**
- Install Sentry package
- Install pods
- Build 

**Actual result:**

Build fails

**Expected result:**

Build does not fail

**Comment by kahest** [comment]
Hey @Mitch528 thanks for writing in - this was already [fixed in the sentry-cocoa SDK](https://github.com/getsentry/sentry-cocoa/issues/4050). Please note that it will take a few days to get that released on sentry-cocoa and then dependency bumped and released here as well.

**Comment by krystofwoldrich** [comment]
Fix was released in https://github.com/getsentry/sentry-cocoa/releases/tag/8.29.0
Let's use this version in the RN SDK.

**Comment by Melber17** [comment]
@kahest Counting on you!

**Comment by 3DTOPO** [comment]
I ran `pod update` and now get a different error with Xcode 16 beta 1:

@_implementationOnly import _SentryPrivate
No such module '_SentryPrivate

**Comment by hannojg** [comment]
I used the new version 8.29.0, and now getting these errors

![Screenshot 2024-06-16 at 13 43 15](https://github.com/getsentry/sentry-react-native/assets/16821682/b4e66921-aa29-4275-9fc4-737fd117d6e3)

**Comment by PraneethGunas** [comment]
Can we have a temporary workaround until the fix is released?

**Comment by TrustDec** [comment]
Hi, is there any update progress? Or a temporary solution?

**Comment by krystofwoldrich** [comment]
Hello everyone, we will release 5.24.0 later today which will be compatible with Xcode 16.

**Comment by venables** [comment]
Just a quick heads up that 5.24.0 does *not* include the fix for this issue, but the main branch does include it from #3890 https://github.com/getsentry/sentry-react-native/pull/3890

**Comment by taxilian** [comment]
Is there a way to install the pre-release from the main branch which supports xcode 16?

**Comment by TrustDec** [comment]
I have updated the version to 5.24.0, but I still haven't solved this problem. When will the main branch push the new version?

**Comment by krystofwoldrich** [comment]
Sentry RN SDK https://github.com/getsentry/sentry-react-native/releases/tag/5.24.1 includes the Xcode 16 `sentry-cocoa` fix.

**Comment by agallio** [comment]
I still have the issue in Xcode 16.0 RC. Using @sentry/react-native 5.24.1. Is there any workaround to fix this? I tried to patch the package to use `Sentry/HybridSDK` version 8.36.0, but no luck.

![Image](https://github.com/user-attachments/assets/1a396448-b927-46ba-bb87-4dbd85947fca)

**Comment by diazgonza17** [comment]
I had the same problem with the Rollbar pod and I fixed it adding a post install script that adds @alitsvin `#include <exception>` to the file causing the error, modify the target name and path accordingly

```
  installer.pods_project.targets.each do |target|
    if target.name == 'Rollbar'
      file_path = 'Pods/Rollbar/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp'
      contents = File.read(file_path)
      unless contents.include?('#include <exception>')
        File.open(file_path, 'w') do |file|
          file.puts('#include <exception>')
          file.puts(contents)
        end
      end
    end
  end
```

**Comment by zaxoavoki** [comment]
For those who have XCode 16 and using Expo, you can do the following:

1. Bump `@sentry/react-native` package version to at least 5.31.0
2. Add `"APPLICATION_EXTENSION_API_ONLY": "NO"` to your `app.config.ts`
```
{
  ...,
  "plugins": [
    [
      ...,
      "expo-build-properties",
      {
        "ios": {
          "buildSettings": {
            "APPLICATION_EXTENSION_API_ONLY": "NO"
          }
        }
      }
    ]
  ]
}
```

**Comment by marcell6** [comment]
> [@bill-florio](https://github.com/bill-florio) [@agallio](https://github.com/agallio) [@marcell6](https://github.com/marcell6) For building with **Xcode 16** you need to
> 
> * Use `@sentry/react-native` version 5.31.0 or newer.
> * Set APPLICATION_EXTENSION_API_ONLY=YES for Sentry like so:
> 
> ```
>     target.build_configurations.each do |config|
>       if target.name != "Sentry"
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
> ```
> 
> We're investigating how we can make the second step unnecessary.

but the newest sentry not support for my react native 0.61.5, any other ways?

**Comment by kahest** [comment]
@marcell6 the oldest RN version we support with version 5.x of the SDK is 0.65. For comparison, Meta officially supports [0.73.x and newer](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#what-versions-are-currently-supported). It is strongly recommended you upgrade the RN version you use.

**Comment by suryav1012** [comment]
Mac OS: 15 Sequoia & XCODE-16 

Fix: 

update sentry version to "@sentry/react-native": "^5.31.0",
 
yarn install
 
pod update
 
clean build folder
 
build again

**Comment by ariq-d** [comment]
> I still have the issue in Xcode 16.0 RC. Using @sentry/react-native 5.24.1. Is there any workaround to fix this? I tried to patch the package to use `Sentry/HybridSDK` version 8.36.0, but no luck.
> 
> ![Image](https://github.com/user-attachments/assets/1a396448-b927-46ba-bb87-4dbd85947fca)

My RN app was working fine until I upgraded to Mac OS Sequoia and Xcode 16, then got this same error even though in the project I didn't install `@sentry/react-native` package, tried `pod update` and `yarn upgrade` but the error still persist. How do I fix this? Tried other solutions here also didn't work.

**Comment by fbeccaceci** [comment]
Using version 5.33.1 everything builds correctly but i cannot get the js/ts sourcemaps to be uploaded automatically when building on ios

**Comment by DevLalla** [comment]
> Mac OS: 15 Sequoia & XCODE-16
> 
> Fix:
> 
> update sentry version to "@sentry/react-native": "^5.31.0",
> 
> yarn install
> 
> pod update
> 
> clean build folder
> 
> build again



**
Amazing! 
Life Saved on Deployment Day
♥️
**

**Comment by tochfrogmi** [comment]
i change the solution @diazgonza17 to 

      if target.name == 'Rollbar'
         file_path = 'Pods/Rollbar/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp'

         if File.exist?(file_path)
            contents = File.read(file_path)
            unless contents.include?('#include <exception>')
               File.open(file_path, 'w') do |file|
                  file.puts('#include <exception>')
                  file.puts(contents)
               end
            end
         else
            puts "El archivo no existe: #{file_path}"
         end
      end

this is working for me in this version using xcode 16 and multi module project

**Comment by duynghiale** [comment]
What are the steps to fix this problem?

**Comment by david-saint** [comment]
Is there a way to resolve this without upgrading to ^v5.31.0?
I'm currently on ^1.7.2, so upgrading will be a nightmare.

**Comment by marcell6** [comment]
@david-saint yes I also did manual like you haha, when upgrading sentry, it worked, but the map source is just empty and useless 🤣, the latest version doesn't support my react native 0.61.5, so the best way for me is like you did

**Comment by chimiWangchukWangdi** [comment]
This is still happening in Expo, I just updated to the latest Xcode and the issue started. Why is this closed?

**Comment by alexkendall** [comment]
Still happening for me. XCode Version 16.0 (16A242d) React-Native 0.74.2

**Comment by kahest** [comment]
@chimiWangchukWangdi @alexkendall which versions of @sentry/react-native do you use? Xcode support has been added in 5.31.0. Note that you might need to manually clean pods to ensure the correct version of sentry-cocoa is used - see [above](https://github.com/getsentry/sentry-react-native/issues/3883#issuecomment-2364165488).

**Comment by chimiWangchukWangdi** [comment]
@kahest I am not using @sentry/react-native, but maybe some of the packages has dependency. Do I need to update that package? I guess it will be a tough work to find that.

**Comment by alexu96** [comment]
> Mac OS: 15 Sequoia & XCODE-16
> 
> Fix:
> 
> update sentry version to "@sentry/react-native": "^5.31.0",
> 
> yarn install
> 
> pod update
> 
> clean build folder
> 
> build again

This solves the issue but I had to upgrade my sentry version from `3.1.1` to `5.31.0` . Is there any other way to fix this without upgrading the sentry ?

**Comment by 3DTOPO** [comment]
Xcode 16 was released 6 months ago. Why is this still happening?

What is the recommended fix, I don't mind running the latest version of Sentry.

**Comment by 3DTOPO** [comment]
Never mind. In my Podfile using:

`pod 'Sentry'`

Allowed it to build. I was using:

```
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
pod 'SentryPrivate', :git => 'https://github.com/getsentry/sentry-cocoa.git'
```

**Comment by sp0033212000** [comment]
I also have this problem in our legacy project that is using react-native 0.63.4 with sentry/react-native 2.6.2
Is there any way to solve this problem without bumping sentry version to the latest one?

**Comment by a-eid** [comment]
this is still an issue for us.

**Comment by krystofwoldrich** [comment]
Hi @a-eid,
could you share what version of the RN SDK are you using?

**Comment by krystofwoldrich** [comment]
Xcode 16 is supported by the Sentry React Native SDK https://github.com/getsentry/sentry-react-native/releases/tag/5.24.1 and newer.

We won't be patching older releases of the SDK, please upgrade to newer SDK versions to support Xcode 16.

---

As a temporary fix you can copy fixes we made in he `sentry-cocoa` to support Xcode 16 as mentioned in https://github.com/getsentry/sentry-react-native/issues/3883#issuecomment-2420468886  

--- 

You can use the following function in your `Podfile` automatically patches the files, but use it with caution as it's not safe to edit edit the source files.

```ruby
...

  post_install do |installer|
    react_native_post_install(...)

    unsafe_patch_old_sentry_for_xcode_16()
  end

...

def unsafe_patch_old_sentry_for_xcode_16
  file_SentryCrashMonitor_CPPException = File.join(__dir__, "Pods/Sentry/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp")
  add_to_SentryCrashMonitor_CPPException = "#include <exception>\n"

  file_SentryCrashMachineContext = File.join(__dir__, "Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c")
  add_to_SentryCrashMachineContext = "#include <sys/_types/_ucontext64.h>\n"

  original_content_SentryCrashMonitor_CPPException = File.read(file_SentryCrashMonitor_CPPException)
  unless original_content_SentryCrashMonitor_CPPException.include?(add_to_SentryCrashMonitor_CPPException.strip)
    File.open(file_SentryCrashMonitor_CPPException, "w") do |file|
      file.puts add_to_SentryCrashMonitor_CPPException + original_content_SentryCrashMonitor_CPPException
    end
    puts "[Sentry] Patched file: #{file_SentryCrashMonitor_CPPException}"
  else
    puts "[Sentry] No patch needed for: #{file_SentryCrashMonitor_CPPException}"
  end

  original_content_SentryCrashMachineContext = File.read(file_SentryCrashMachineContext)
  unless original_content_SentryCrashMachineContext.include?(add_to_SentryCrashMachineContext.strip)
    File.open(file_SentryCrashMachineContext, "w") do |file|
      file.puts add_to_SentryCrashMachineContext + original_content_SentryCrashMachineContext
    end
    puts "[Sentry] Patched file: #{file_SentryCrashMachineContext}"
  else
    puts "[Sentry] No patch needed for: #{file_SentryCrashMachineContext}"
  end
end

```

**Comment by a-eid** [comment]
@krystofwoldrich I was using  `RN 76`, upgrading to sentry 6 fixed the issue.

**Comment by biancag113** [comment]
> @sentry/react-native": "^5.31.0"

Thank you so much! This worked.

**Comment by kjgetcarnera** [comment]
No type named 'terminate_handler' in namespace 'std'
No member named 'set_terminate' in namespace 'std'
No type named 'set_terminate' in namespace 'std'

React Native - iOS - after updating the Xcode for version 16.2 from 15.4 

Please follow below steps to solved the issue : 

step 1 -  
npm i @sentry/react-native@5.32.0

step 2 -  
go to iOS folder and 
a. Execute -   pod install --repo-update
b. Execute -  pod update Sentry/HybridSDK

step 3 -  
Open Xcode - clear derive data , clean and build project and run

**Comment by krystofwoldrich** [comment]
Hi @kjgetcarnera,
does it also happen with the latest SDK version?

May be related to https://github.com/getsentry/sentry-react-native/issues/4622, we have not been able to reproduce the build failure with the latest SDK.
