### ISSUE TITLE
1.0.0 broke iOS compilation

### ISSUE THREAD

**Issue by Strayer** [getsentry/sentry-react-native#648]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.16.0
6.9.0
Redacted@0.0.1 /redacted
├── @react-native-community/geolocation@1.4.2
├── @sentry/react-native@1.0.0
├── apollo-cache-inmemory@1.5.1
├── apollo-cache-persist@0.1.1
├── apollo-client@2.5.1
├── apollo-link@1.2.11
├── apollo-link-batch-http@1.2.11
├── apollo-link-context@1.0.17
├── apollo-link-error@1.1.10
├── apollo-utilities@1.2.1
├── async-mutex@0.1.3
├── buffer@5.2.1
├── graphql@14.2.1
├── graphql-tag@2.10.1
├── react@16.8.6
├── react-apollo@2.5.5
├── react-native@0.60.5
├── react-native-background-fetch@2.7.0
├── react-native-background-geolocation-android@3.2.1 invalid
├── react-native-config@0.11.7 invalid
├── react-native-firebase@5.5.6
├── react-native-geolocation-service@3.1.0
├── react-native-gesture-handler@1.4.1
├── react-native-hyperlink@0.0.14
├── react-native-qrcode-svg@5.2.0
├── react-native-snap-carousel@3.8.0
├── react-native-svg@9.8.3
├── react-native-swiper@1.5.14
├── react-native-vector-icons@6.6.0
├── react-native-version-number@0.3.6
└── react-navigation@3.9.1

npm ERR! invalid: react-native-background-geolocation-android@3.2.1 /redacted/node_modules/react-native-background-geolocation-android
npm ERR! extraneous: plist@2.1.0 /redacted/node_modules/react-native-background-geolocation-android/node_modules/plist
npm ERR! extraneous: xcode@0.9.3 /redacted/node_modules/react-native-background-geolocation-android/node_modules/xcode
npm ERR! invalid: react-native-config@0.11.7 /redacted/node_modules/react-native-config
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/babel-preset-fbjs/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/helper-create-class-features-plugin/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/plugin-syntax-nullish-coalescing-operator/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/plugin-syntax-optional-catch-binding/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/plugin-syntax-optional-chaining/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/metro-react-native-babel-transformer/node_modules/metro-react-native-babel-preset/node_modules/@babel/core
npm ERR! extraneous: @babel/core@7.4.4 /redacted/node_modules/@babel/plugin-syntax-typescript/node_modules/@babel/core
```

---

iOS compilation fails with these build errors:

```
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:125:17: error: use of undeclared identifier 'scope'; did you mean 'bcopy'?
    if (nil != [scope objectForKey:@"__sentry_release"]) {
                ^~~~~
                bcopy
In module 'Darwin' imported from /redacted/ios/Pods/Headers/Public/React-Core/React/RCTUtils.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk/usr/include/strings.h:71:7: note: 'bcopy' declared here
void     bcopy(const void *, void *, size_t) __POSIX_C_DEPRECATED(200112L);
         ^
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:125:17: error: bad receiver type 'void (*)(const void *, void *, size_t)' (aka 'void (*)(const void *, void *, unsigned long)')
    if (nil != [scope objectForKey:@"__sentry_release"]) {
                ^~~~~
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:126:50: error: use of undeclared identifier 'scope'; did you mean 'bcopy'?
        SentryClient.sharedClient.releaseName = [scope objectForKey:@"__sentry_release"];
                                                 ^~~~~
                                                 bcopy
In module 'Darwin' imported from /redacted/ios/Pods/Headers/Public/React-Core/React/RCTUtils.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk/usr/include/strings.h:71:7: note: 'bcopy' declared here
void     bcopy(const void *, void *, size_t) __POSIX_C_DEPRECATED(200112L);
         ^
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:126:50: error: bad receiver type 'void (*)(const void *, void *, size_t)' (aka 'void (*)(const void *, void *, unsigned long)')
        SentryClient.sharedClient.releaseName = [scope objectForKey:@"__sentry_release"];
                                                 ^~~~~
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:128:17: error: use of undeclared identifier 'scope'; did you mean 'bcopy'?
    if (nil != [scope objectForKey:@"__sentry_dist"]) {
                ^~~~~
                bcopy
In module 'Darwin' imported from /redacted/ios/Pods/Headers/Public/React-Core/React/RCTUtils.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk/usr/include/strings.h:71:7: note: 'bcopy' declared here
void     bcopy(const void *, void *, size_t) __POSIX_C_DEPRECATED(200112L);
         ^
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:128:17: error: bad receiver type 'void (*)(const void *, void *, size_t)' (aka 'void (*)(const void *, void *, unsigned long)')
    if (nil != [scope objectForKey:@"__sentry_dist"]) {
                ^~~~~
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:129:43: error: use of undeclared identifier 'scope'; did you mean 'bcopy'?
        SentryClient.sharedClient.dist = [scope objectForKey:@"__sentry_dist"];
                                          ^~~~~
                                          bcopy
In module 'Darwin' imported from /redacted/ios/Pods/Headers/Public/React-Core/React/RCTUtils.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk/usr/include/strings.h:71:7: note: 'bcopy' declared here
void     bcopy(const void *, void *, size_t) __POSIX_C_DEPRECATED(200112L);
         ^
/redacted/node_modules/@sentry/react-native/ios/RNSentry.m:129:43: error: bad receiver type 'void (*)(const void *, void *, size_t)' (aka 'void (*)(const void *, void *, unsigned long)')
        SentryClient.sharedClient.dist = [scope objectForKey:@"__sentry_dist"];
                                          ^~~~~
8 errors generated.


** BUILD FAILED *
```

This issue was introduced by eee70830cbe7b001048f3dc4215fed428a93ca4e.

**Comment by n4kz** [comment]
Looks like typo, `scope` should be renamed to `extra`

**Comment by HazAT** [comment]
Sorry about that, fixed in `1.0.1`  which should be released in <5min.
