### ISSUE TITLE
TypeError: RNSentry.getNewScreenTimeToDisplay is not a function (it is undefined)

### ISSUE THREAD

**Issue by harsh-mishra1-PSL** [getsentry/sentry-react-native#4434]
### What React Native libraries do you use?

React Navigation, Expo (mobile only), Expo Web

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

^6.1.0

### How does your development environment look like?

OS: Android & iOS
Node: 23.5.0
Yarn: 1.22.22
Expo SDK: 50
React: 18.2.0
react-native: 0.73.6

### Sentry.init()

Sentry.init({
  dsn: process.env.SENTRY_DSN,
  debug: false, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
  tracesSampleRate: 1.0,
  //tracePropagationTargets: ['localhost', /^\//, /^https:\/\//, /^http:\/\//],
  // The time to wait in ms until the transaction will be finished, For testing, default is 1000 ms
  tracePropagationTargets: ['localhost', process.env.GRAPHQL_ENDPOINT || ''],
  attachScreenshot: true,
  attachStacktrace: true,
  attachViewHierarchy: true,
  autoSessionTracking: true,
  // Enables capture failed requests in JS and native.
  enableCaptureFailedRequests: true,
  environment: process.env.SENTRY_ENV,
  spotlight: true,
  beforeSend: (event: Sentry.Event) => {
    return event;
  },
  beforeSendTransaction(event) {
    return event;
  },
  enabled: !__DEV__,
  enableAutoPerformanceTracing: true,
  enableWatchdogTerminationTracking: true,
  //Sets the `release` and `dist` on Sentry events. Make sure this matches EXACTLY with the values on your sourcemaps
  // otherwise they will not work.
  // release: 'myapp@1.2.3+1',
  release: appVersion,
  // dist: `1`,
  enableNativeCrashHandling: true,
  enableAutoSessionTracking: true,
  sessionTrackingIntervalMillis: 5000,
  enableTracing: true,
  enableAppHangTracking: true,
  idleTimeout: 5000,
  enableUserInteractionTracing: true,
  enableTimeToFullDisplayTracing: true,
  ignoreEmptyBackNavigationTransactions: true,
  integrations: [
    reactNavigationIntegration,
    Sentry.reactNativeTracingIntegration({
      beforeStartSpan: (options) => {
        console.log('options:', options);
        return {
          ...options,
          op: 'navigation',
        };
      },
      shouldCreateSpanForRequest: (url) => {
        // Do not create spans for outgoing requests to a `/health/` endpoint
        return !url.match(/\/health\/?$/);
      },
    }),
    Sentry.httpClientIntegration({
      // These options are effective only in JS.
      // This array can contain tuples of `[begin, end]` (both inclusive),
      // Single status codes, or a combinations of both.
      // default: [[500, 599]]
      failedRequestStatusCodes: [[400, 599]],
      // This array can contain Regexes or strings, or combinations of both.
      // default: [/.*/]
      failedRequestTargets: [/.*/],
    }),
    Sentry.mobileReplayIntegration({
      maskAllText: true,
      maskAllImages: true,
    }),
  ],
  _experiments: {
    // The sampling rate for profiling is relative to TracesSampleRate.
    // In this case, we'll capture profiles for 100% of transactions.
    profilesSampleRate: 1.0,
    replaysSessionSampleRate: 1.0,
    replaysOnErrorSampleRate: 1.0,
  },
});

### Steps to Reproduce

1.  Start expo using `yarn expo -c`.
2. Press `i` for building iOS. 

### Expected Result

Should works perfectly fine.

### Actual Result

Crashes on initial render of screen. 

Error: TypeError: RNSentry.getNewScreenTimeToDisplay is not a function (it is undefined)

What causes issue:
After migration from 5x to 6x in react native.

Occurrence of error in code:

Sentry.reactNavigationIntegration({
        enableTimeToInitialDisplay: true, // if removed then works fine.
      })

in `Navigation file`:
import {
  createNavigationContainerRef,
  DefaultTheme,
  NavigationContainer,
} from '@react-navigation/native';
import { ComponentProps } from 'react';
import { enableFreeze } from 'react-native-screens';

import { reactNavigationIntegration } from '../../App';
import theme from '../../themes/theme';

const navigationTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: theme.colors.white,
  },
};

enableFreeze(true);

type Props = Omit<ComponentProps<typeof NavigationContainer>, 'theme'>;

export const ThemedNavigationContainer = (props: Props) => {
  const navigation = createNavigationContainerRef();
  return (
    <NavigationContainer
      {...props}
      ref={navigation}
      theme={navigationTheme}
      onReady={() => {
        if (navigation.isReady() && reactNavigationIntegration) {
          reactNavigationIntegration.registerNavigationContainer(navigation); // if removed works fine
        }
      }}
    />
  );
};

![Image](https://github.com/user-attachments/assets/a6b1c481-47a8-46c5-a116-94d88ac897b6)

**Comment by krystofwoldrich** [comment]
Hi @harsh-mishra1-PSL,
thank you for the message and all the details. 

The native implementation is out of sync with your JS code. Please rebuild the native part of the application (including pod install on iOS) and check if the issue persists.

Let us know if this helped.

**Comment by harsh-mishra1-PSL** [comment]
Hi @krystofwoldrich 
Yes, It worked. Thanks
