### PR TITLE
fix(ios): Restore ObjC SentrySwizzle for RNSScreen to link against xcframework

### LINKED ISSUE #6465: iOS build fails to link (Undefined symbols: SentryInternalSwizzleApi.Mode.oncePerClass) when consuming the default prebuilt Sentry.xcframework
### What React Native libraries do you use?

Expo Application Services (EAS), Expo (mobile only), Hermes

### Are you using [sentry.io](<http://sentry.io>) or on-premise?

[sentry.io](<http://sentry.io>) (SaS)

### Are you using any other error monitoring solution alongside Sentry?

Yes

### Other Error Monitoring Solution Name

*No response*

### @sentry/react-native SDK Version

8.19.0

### How does your development environment look like?

```
@sentry/react-native: 8.19.0
sentry-cocoa (pinned by RNSentry RNSentry.podspec): 9.19.1
react-native: 0.83.6
expo: 55.0.27
Build: EAS Build, iOS sdk-55 image, device (arm64) release build
SENTRY_USE_XCFRAMEWORK: unset (i.e. the new default prebuilt-xcframework path)
```

### Sentry.init()

```js
Sentry.init({
  dsn: "https://XXX@oXXXX.ingest.us.sentry.io/XXXX",
  release: getSentryReleaseIdentifier(),
  profilesSampleRate: 1.0,
  environment: getEnvironment(),
  attachScreenshot: false,
  attachViewHierarchy: false,
  attachThreads: true,
  attachAllThreads: true,
  dist: Updates.updateId ?? undefined,
});
```

### Steps to Reproduce

1. Use @sentry/react-native 8.19.0 on iOS with the default integration (prebuilt Sentry.xcframework; SENTRY_USE_XCFRAMEWORK unset).
2. Build the iOS app for a real device (arm64). Ours is an Expo (CNG) app built on EAS Build ([JS-1173](https://linear.app/getsentry/issue/JS-1173/add-node-and-server-sdk-poc-implementation) image).
3. The Xcode/ld link step fails (see Actual Result). Setting SENTRY_USE_XCFRAMEWORK=0 (source build) makes it succeed.

### Expected Result

The app links against the prebuilt Sentry.xcframework and builds successfully, with no need to fall back to the source-built CocoaPod.

### Actual Result

Link step fails:

```
Undefined symbols for architecture arm64
┌─ Symbol: enum case for Sentry.SentryInternalSwizzleApi.Mode.oncePerClass(Sentry.SentryInternalSwizzleApi.Mode.Type) -> Sentry.SentryInternalSwizzleApi.Mode
└─ Referenced from: function signature specialization <Arg[1] = Dead> of static RNSentry.RNSentryInternal.swizzleRNSScreenViewDidAppear(hook: () -> ()) -> () in RNSentry[28](RNSentryInternal.o)

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Likely cause is the interaction of two changes that landed for 8.18/8.19:

* getsentry/sentry-react-native#6380, migrating iOS from PrivateSentrySDKOnly to SentrySDK.internal, which introduced the SentryInternalSwizzleApi reference in RNSentryInternal.swizzleRNSScreenViewDidAppear.
* getsentry/sentry-react-native#6413 / getsentry/sentry-react-native#6381, making the prebuilt Sentry.xcframework the default (getsentry/sentry-react-native#6080).

SentryInternalSwizzleApi.Mode.oncePerClass is an internal/@_spi Swift symbol that the prebuilt static Sentry.xcframework slice doesn’t vend, so RNSentry (compiled separately) can’t resolve it at link time. Building sentry-cocoa from source (SENTRY_USE_XCFRAMEWORK=0) keeps both in the same module graph and links cleanly.

### PR DESCRIPTION
**Pull request by alwx**
## 📢 Type of change

- [X] Bugfix

## 📜 Description

Restore the `SentrySwizzle` ObjC path for the `RNSScreen viewDidAppear:` swizzle. The Swift `SentrySDK.internal.swizzle` API introduced in getsentry/sentry-react-native#6380 references `SentryInternalSwizzleApi.Mode.oncePerClass`, an `@_spi(Private)` enum case whose metadata symbol is not exported from sentry-cocoa's prebuilt static xcframework — compile succeeds via `.private.swiftinterface`, but link fails on arm64.

The ObjC `SentrySwizzle` class + `SentrySwizzleMode` enum export normally (`_OBJC_CLASS_$_SentrySwizzle` verified in the arm64 slice), so this call site links cleanly for both the xcframework default and the source-built `SENTRY_USE_XCFRAMEWORK=0` fallback. The rest of the `SentrySDK.internal` migration in getsentry/sentry-react-native#6380 keeps using the Swift bridge.

## 💡 Motivation and Context

Fixes getsentry/sentry-react-native#6465.

## :pencil: Checklist

- [ ] I added tests to verify changes.
- [X] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [X] I updated the docs if needed.
- [X] I updated the wizard if needed.
- [ ] All tests passing.
- [X] Public API changes reviewed by another Mobile SDK team member or implemented according to the [develop docs](<https://develop.sentry.dev/>) spec.
- [X] No breaking changes.

## 🔮 Next steps

### CODE REVIEW

**Comment by lucas-zimerman** [comment]
Should we close this PR? it seems the root cause was done by user error.

**Comment by philprime** [comment]
The problem seems to be resolved:

> Ahhh shoot. Sorry! It turns out an internal native dependency had `s.dependency 'Sentry', '~> 9.0'` in the podspec, so it looks like we were running into a two-Sentry-provider ABI mismatch. `SENTRY_USE_XCFRAMEWORK=0` was letting us compile against the same source module and bypass the mismatch

Ref: https://github.com/getsentry/sentry-react-native/issues/6465#issuecomment-5024113057

**Comment by alwx** [comment]
Closing it. Thanks @philprime for taking a look!
