### ISSUE TITLE
Build with 0.43.2 failed on Android : package android.support.annotation does not exist

### ISSUE THREAD

**Issue by lc3t35** [getsentry/sentry-react-native#638]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.16.0
6.9.0
├── react-native-sentry@0.43.2
```
---
I'm building a detached Expo app with react-native-sentry 0.43.2 (works fine with iOS)
I have the following message 
```
> Task :react-native-sentry:compileDebugJavaWithJavac FAILED
/Users/***/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/***/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java:302: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNSentryModule
Note: /Users/***/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

**Steps to reproduce:**
- react-native link react-native-sentry
- ./gradlew installDebug

**Quick analysis:**
- the file RNSentryModule.java has at line 6
```
import android.support.annotation.NonNull
```
used at line 302 : @NonNull for private UserBuilder

In 1.0.0-beta, this annotation has been removed.

**Comment by silentlight** [comment]
I have the same problem. Anyone found a fix for it?

**Comment by lc3t35** [comment]
Yep ! Waiting 2 weeks is not possible ... so I moved to bugsnag ... alles in ordnung !

**Comment by olivergeorge** [comment]
This was what got me there in the end
https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Fitnext.io%2Freact-native-how-to-handle-an-app-with-both-pre-androidx-and-androidx-dependencies-rn60-bf4df7ea0dd2

**Comment by HugoLiconV** [comment]
`vi node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java`

and replace `android.support.annotation.NonNull` for `import androidx.annotation.NonNull`

**Comment by HazAT** [comment]
Hey, sorry for the late response.
Please use `@sentry/react-native` the annotation is gone there.

**Comment by piyushrajput45** [comment]
react native build error:- import android.support.annotation.NonNull
go to the terminal and open your project

Step 1- npm install jetifier

You can use yarn, but install it locally in your project, not globally

Step 2- npx jetify

Step 3- npx react-native run-android
