### PR TITLE
fix(ios): [RN 0.87] remove unused React/RCTTextView.h import

### PR DESCRIPTION
**Pull request by cortinico**
## :loudspeaker: Type of change
- [x] Bugfix

## :scroll: Description

> [!IMPORTANT]  
> This is needed for this library to work with RN 0.87. Please review/merge and publish a new version of the sentry library on NPM if possible.

`packages/core/ios/RNSentryReplay.mm` imported `React/RCTTextView.h`, which has been removed from React Native 0.87 as part of the legacy architecture cleanup ([facebook/react-native#56831](https://github.com/facebook/react-native/pull/56831)). This breaks the iOS build with:

```
RNSentryReplay.mm:5:9: fatal error: 'React/RCTTextView.h' file not found
```

The import was **unused** — `RCTTextView` is only referenced as the runtime string `@"RCTTextView"` when building the Session Replay redaction class list, so no symbol from the header is needed (`@"RCTParagraphComponentView"` already covers the Fabric text view). Removing the import restores the build on RN 0.87 while keeping masking behavior identical on older RN versions.

## :bulb: Motivation and Context

React Native 0.87 (currently nightly) deleted `Libraries/Text/Text/RCTTextView.h`, so any app using `@sentry/react-native` fails to compile on iOS. Surfaced by the React Native community nightly tests.

https://react-native-community.github.io/nightly-tests/

## :green_heart: How did you test it?
- Static verification: `RCTTextView` is no longer referenced as a type/symbol anywhere in `RNSentryReplay.mm`; the only remaining usage is the string literal `@"RCTTextView"` for replay masking, which is unchanged.
- Not run in this branch: the full iOS native build / CI (no behavioral change to test beyond compilation).

## :pencil: Checklist
- [x] I added tests to verify changes
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by cortinico** [comment]
This is ready for review 🙏

**Review by antonis — APPROVED** [review]
LGTM 🎸 
Thank you for your contribution @cortinico 🙇 
This will ship in our next release later this week.

ps. I took the liberty of resolving a minor changelog conflict to unblock merging

**Comment by cortinico** [comment]
> LGTM 🎸 Thank you for your contribution @cortinico 🙇 This will ship in our next release later this week.

Thanks for merging this. Looking forward to getting a new release
